<?php

namespace AppBundle\Repository;

/**
 * AsteroidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsteroidRepository extends \Doctrine\ORM\EntityRepository
{
}
