<?php

namespace AppBundle\Repository;

/**
 * ISSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ISSRepository extends \Doctrine\ORM\EntityRepository
{
}
