<?php

namespace AppBundle\Repository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAllByDate()
    {
        // get astronomy pictures ordered by date
        return $this->findBy([], ['date' => 'DESC']);
    }
}
