<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends EntityRepository
{
    /**
     * Gets astronomy pictures ordered by date.
     *
     * @return array
     */
    public function findAllByDate(): array
    {
        return $this->findBy([], ['date' => 'DESC']);
    }
}
