<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * PlanetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @ORM\Entity
 * @ORM\Table(name="planet_repository")
 */
class PlanetRepository extends EntityRepository
{
    public function findPlanets()
    {
        return $this->createQueryBuilder('planet')
            ->select('planet.name')
            ->getQuery()
            ->execute();
    }
}
