<?php

namespace AppBundle\Repository;

/**
 * PlanetScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
