<?php

namespace AppBundle\Repository;

/**
 * PlanetArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
