<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Planet;
/**
 * PlanetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetRepository extends EntityRepository
{
    public function findAllPlanets()
    {
        return $this->createQueryBuilder('planet')
            ->select('planet.name')
            ->getQuery()
            ->execute();
    }

}
