<?php

namespace AppBundle\Repository;

/**
 * RoverPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoverPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
